### PR TITLE
Create Farm Screens and User Flow

### PR DESCRIPTION
**Pull request by PreyanshK**
This PR does the following:

- Created MVVM for Create Farm and Farm Code screens
- Restricted navigation to Create Farm screen only if the user's FarmID is Empty or NULL
- Calls the Farm Repository function to create a new farm on Firestore
- Refactors Farm Repository to use the new Repository Response sealed class for try-catch

Demo:
https://github.com/adshayanB/ECE452/assets/36520183/85cb16f5-5572-47c9-8c46-579e80d9c4de

### CODE REVIEW

**Review by adshayanB — APPROVED** [review]
Looks good to me! 

Verified the changes on the db side of things it looks good :)

**Comment by PreyanshK** [comment]
@RishanR when you have capacity on your time table, can you review this PR

**Review by SathursanS — APPROVED** [review]
LGTM

**Review by RishanR — APPROVED** [review]
Looks good! Ship it :shipit:

**Pull request merged**
