### PR TITLE
Refactored transaction repo to support firestore

### PR DESCRIPTION
**Pull request by adshayanB**
Refactored transaction repo to support firestore.

The PR covers the following:
- Performs query based on the newly created firestore index to pull recent transaction data
- Pull and view recent transaction data via firestore
- Delete transactions and intergated it to support the current delete page 
- Add transactions and update list of trasnaction ids for the particular farm.

Current Index for Querying looks like this: 
image

Note: farmId ascending does not matter, as we pick the where equal to clause for that

### CODE REVIEW

**Comment by adshayanB** [comment]
It to also note that @SoumilDharaskar will handle the adding the response class in his views, to streamline the development process with no hiccups, as he is working on the transaction filtering views at the same time.

**Review by RishanR — APPROVED** [review]
Looks good! But I noticed that the Transactions Repositor doesn't seem to be returning FAResponses. Are we refactoring this in a later PR?

**Comment by adshayanB** [comment]
> Looks good! But I noticed that the Transactions Repository doesn't seem to be returning FAResponses. Are we refactoring this in a later PR?

As mentioned in the below comment, @SoumilDharaskar will be doing the Responses as hes working on the views right now

**Comment by RishanR** [comment]
> > Looks good! But I noticed that the Transactions Repository doesn't seem to be returning FAResponses. Are we refactoring this in a later PR?
> 
> As mentioned in the below comment, @SoumilDharaskar will be doing the Responses as hes working on the views right now

Ohhh I see completely missed that. Thank you :)

**Pull request merged**
