### PR TITLE
Added filter pills for transactions page

### PR DESCRIPTION
**Pull request by SoumilDharaskar**
image

Still need to work on the actual filtering flow, but have generated the filter pills with items under different categories such as Markets, Transactions, Produce.

### CODE REVIEW

**Review by adshayanB — APPROVED** [review]
LGTM! Thank you for breaking this into smaller prs

Looking forward to your next one!

Just a question, why are you using two github accounts, this may mess up your commit history when TA's are marking, might be a better option to stick to one main account.

**Review by adshayanB — COMMENTED** [review]
Please add a time log of the work done for this PR, It is nice to include a timelog with all your Pr;s so you wont forget

**Comment by SoumilDharaskar** [comment]
> LGTM! Thank you for breaking this into smaller prs
> 
> Looking forward to your next one!
> 
> Just a question, why are you using two github accounts, this may mess up your commit history when TA's are marking, might be a better option to stick to one main account.

Yea it's actually an issue with my ssh keys so for some reason it doesn't register my actual github account when I push from my laptop. I tried fixing it but wasn't able to resolve it so I communicated this to the TAs and they were ok with the two accounts

**Comment by SoumilDharaskar** [comment]
> Please add a time log of the work done for this PR, It is nice to include a timelog with all your Pr;s so you wont forget

Yep will do that! Thanks

**Comment by neelp1030** [comment]
We are making it so that each transaction will only relate to a single produce right? So if a harvest is submitted for apples, oranges, and bananas, there will be 3 separate transactions created for that one harvest?

**Comment by neelp1030** [comment]
Also, I think it might be valuable to modify the filter pill structure as follows (if it's not too much trouble): transaction type filter and produce filter can always be shown, since they are common across all transaction types. However, the filter you have for market is really only relevant for the SELL transaction type. For this reason, here's my recommendation:

1) Transaction Type Filter
2) Produce Filter
3) Market Filter
4) Charity Filter

1) and 2) are always displayed. 3) is only displayed if 1) is set to ALL or SELL. 4) is only displayed if 1) is set to ALL or DONATE.

Does this make sense? Would love to hear other people's input on this too.

**Comment by adshayanB** [comment]
> Also, I think it might be valuable to modify the filter pill structure as follows (if it's not too much trouble): transaction type filter and produce filter can always be shown, since they are common across all transaction types. However, the filter you have for market is really only relevant for the SELL transaction type. For this reason, here's my recommendation:
> 
> 1. Transaction Type Filter
> 2. Produce Filter
> 3. Market Filter
> 4. Charity Filter
> 
> 1 and 2 are always displayed. 3 is only displayed if 1 is set to ALL or SELL. 4 is only displayed if 1 is set to ALL or DONATE.
> 
> Does this make sense? Would love to hear other people's input on this too.

I like this idea @RishanR what are your thoughts?

**Comment by RishanR** [comment]
> > We are making it so that each transaction will only relate to a single produce right? So if a harvest is submitted for apples, oranges, and bananas, there will be 3 separate transactions created for that one harvest?
> 
> Yes, we did that for simplicity. It would also be easier to do this when we want to undo

Yup, I 💯 agree with this!

**Review by RishanR — APPROVED** [review]
Looking good! Just add the change Neel mentioned about showing certain filters when certain conditions are met :)

**Pull request merged**
